"""empty message

Revision ID: ae17805f4c39
Revises: 3e1e72d79c8f
Create Date: 2024-03-04 07:10:07.074669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae17805f4c39'
down_revision: Union[str, None] = '3e1e72d79c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name_of_project', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'name_of_project')
    # ### end Alembic commands ###
